/**
 * Workflow app — shared mutable runtime state.
 */
(function () {
    'use strict';

    window.WorkflowRuntime = {
        POLL_MS: 2500,
        API: '',
        WF_STORAGE_KEY: 'workflow-active-v1',
        NODE_LABELS: {
            setup: 'Make setup',
            intro: 'Make intro',
            record: 'Record',
            bracket: 'Bracket',
            powerup: 'Powerup',
            compose: 'Compose',
            youtube: 'YouTube',
            tournament: 'Tournament',
        },
        SETUP_STORAGE_KEY: 'workflow-setup-v1',
        LONG_SETUP_STORAGE_KEY: 'workflow-setup-long-v1',
        BRACKET_STORAGE_KEY: 'workflow-bracket-v1',
        MATCH_COMPOSE_STORAGE_KEY: 'workflow-match-compose-v1',
        TOURNAMENT_ROSTER_STORAGE_KEY: 'workflow-tournament-roster-v1',
        TOURNAMENT_ARENA_STORAGE_KEY: 'workflow-tournament-current-matchup-v1',

        pipeline: null,
        scriptText: '',
        caption: { title: '', description: '', privacy: 'public' },
        scriptDirty: false,
        captionDirty: false,
        busy: false,
        previewNode: 'record',
        /** Monotonic id so slower /api/pipeline responses can't overwrite newer state. */
        pipelineEpoch: 0,
        setupReady: null,
        bracketState: null,
        tournamentPhase: null,
        activeArenaMatchKey: null,
        tournamentFightEvidence: [],
        tournamentMedia: {
            finalReady: false,
            final: null,
            previewReady: false,
            preview: null,
            doneSegmentCount: 0,
            segmentCount: 0,
            status: null,
            error: null,
            progress: null,
        },
        lastLogMsg: '',
        lastProgressMsg: '',
        matchComposeStore: window.TournamentCompose?.createStore?.({
            storage: window.localStorage,
            storageKey: 'workflow-match-compose-v1',
        }) || null,

        els: {
            canvas: document.getElementById('workflow-canvas'),
            switcher: document.getElementById('workflow-switcher'),
            title: document.getElementById('workflow-title'),
            subtitle: document.getElementById('workflow-subtitle'),
            quotaBadge: document.getElementById('quota-badge'),
            quotaUploads: document.getElementById('quota-uploads'),
            serverStatus: document.getElementById('server-status'),
            logText: document.getElementById('log-text'),
            logLines: document.getElementById('log-lines'),
            workflowLog: document.getElementById('workflow-log'),
            previewLabel: document.getElementById('preview-label'),
            previewFile: document.getElementById('preview-file'),
            previewVideo: document.getElementById('preview-video'),
            previewBracket: document.getElementById('preview-bracket'),
            previewArena: document.getElementById('workflow-preview-arena'),
            previewEmpty: document.getElementById('preview-empty'),
            modalScript: document.getElementById('modal-script'),
            modalCaption: document.getElementById('modal-caption'),
            modalSetup: document.getElementById('modal-setup'),
            modalIntro: document.getElementById('modal-intro'),
            inputScript: document.getElementById('input-script'),
            inputTitle: document.getElementById('input-title'),
            inputDescription: document.getElementById('input-description'),
            inputPrivacy: document.getElementById('input-privacy'),
            composeModeBadge: document.getElementById('compose-mode-badge'),
            btnReloadScript: document.getElementById('btn-reload-script'),
            btnReloadCaption: document.getElementById('btn-reload-caption'),
            btnZoomIn: document.getElementById('btn-zoom-in'),
            btnZoomOut: document.getElementById('btn-zoom-out'),
            btnClearAll: document.getElementById('btn-clear-all'),
            btnRestart: document.getElementById('btn-restart'),
            btnSaveMatchup: document.getElementById('btn-save-matchup'),
            canvasWrap: document.querySelector('.workflow-canvas-wrap'),
        },

        canvasView: {
            x: 0,
            y: 0,
            scale: 1,
            minScale: 0.35,
            maxScale: 2.5,
            dot: 22,
        },
    };
}());
